### ISSUE TITLE
Create The FAQ Page

### ISSUE THREAD

**Issue by psalmuelle** [zuri-training/Team-56_QR-GEN-Frontend#4]
I have created empty files that will contain your html and css codes. Follow the design to implement the FAQ Page.
Instructions:
For your media query, follow this strictly->max-width = 640px

The implementation should be exactly the same thing with the design provided -
https://www.figma.com/file/ZQXFCwPUyp1gA4n0AazekM/Team-56_QR-GEN?node-id=723%3A1161

Goodluck! @jogunfuwa

**Comment by jogunfuwa** [comment]
On it already boss. Thanks
