### ISSUE TITLE
Create The Landing Page From The Figma Design

### ISSUE THREAD

**Issue by psalmuelle** [zuri-training/Team-56_QR-GEN-Frontend#6]
I have created empty files that will contain your html and css codes. Follow the design to implement the Landing Page.
Instructions:
For your media query, follow this strictly->max-width = 640px

The implementation should be exactly the same thing with the design provided -
https://www.figma.com/file/ZQXFCwPUyp1gA4n0AazekM/Team-56_QR-GEN?node-id=723%3A1161

Goodluck! @3k3n3

**Comment by 3k3n3** [comment]
@psalmuelle the colours on the style guide dont match the one on the figma designs. Which are we to use?

**Comment by Koboj** [comment]
You are to use the Purple (primary color) and the greys

**Comment by 3k3n3** [comment]
completed
