### ISSUE TITLE
Create Static Qr Page From Our Figma File

### ISSUE THREAD

**Issue by psalmuelle** [zuri-training/Team-56_QR-GEN-Frontend#9]
You will find the design in this link:
https://www.figma.com/file/ZQXFCwPUyp1gA4n0AazekM/Team-56_QR-GEN?node-id=723%3A1161

Also, The header and footer are ready, follow the instructions i sent to the group to copy them to your page. You will have to create your page. Just follow the convention thats being used.
Good Luck @emmaxyz90

**Comment by heisnueljnr** [comment]
@emmaxyz90 what have you done so far please
